# Generated by Django 4.2.14 on 2024-07-17 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='content',
            field=models.TextField(verbose_name='아이디어 설명'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='devtool',
            field=models.CharField(max_length=10, verbose_name='예상 개발툴'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='interest',
            field=models.IntegerField(default=0, verbose_name='아이디어 관심도'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='title',
            field=models.CharField(max_length=24, verbose_name='아이디어명'),
        ),
    ]
