# Generated by Django 4.2.14 on 2024-07-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_user_name_alter_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='pwd',
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
