# Generated by Django 4.2.14 on 2024-07-12 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('direcor', models.CharField(max_length=15)),
                ('leadrole', models.CharField(max_length=15)),
                ('genre', models.CharField(max_length=10)),
                ('evaluation', models.IntegerField(default=0)),
                ('runningtime', models.IntegerField(default=0)),
                ('review', models.TextField()),
            ],
        ),
    ]
