# Generated by Django 4.2.14 on 2024-07-12 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_rename_direcor_movie_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='leadrole',
            field=models.CharField(max_length=50),
        ),
    ]
