# Generated by Django 4.2.14 on 2024-07-12 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movie_evaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='release',
            field=models.IntegerField(default=0),
        ),
    ]
